config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[index show] do
    member do
      get 'verify'
    end
    collection do
      post 'search'
    end
  end

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'
  post '/contact_admin', to: 'users#contact_admin', as: 'contact_admin'
  post '/contact_lawyer', to: 'users#contact_lawyer', as: 'contact_lawyer'

  resources :services, only: %i[index show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :name, use: %i[slugged history]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, :phone_number, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :avatar, presence: { message: "(Profile picture) can't be blank!" }, on: :create
  validate :validate_user_services_uniqueness, on: :create

  before_validation :prepend_adv_to_name, on: %i[create update], if: :add_advocate?

  ROLES = {
    lawyer: 0,
    client: 1,
    admin: 2,
    owner: 3,
    administrator: 4,
  }.freeze

  enum role: ROLES

  PROVINCES = ['Punjab', 'Sindh', 'Khyber Pakhtunkhwa', 'Balochistan'].freeze

  has_one_attached :avatar
  has_one :user_summary, dependent: :destroy
  has_many :user_services, dependent: :destroy
  has_many :services, through: :user_services

  accepts_nested_attributes_for :user_services, allow_destroy: true
  accepts_nested_attributes_for :user_summary

  default_scope { order(created_at: :asc) }
  scope :unverified, -> { joins(:user_summary).where(user_summary: { verified_at: nil }) }
  scope :verified, -> { joins(:user_summary).where.not(user_summary: { verified_at: nil }) }
  scope :created_today, -> { where('Date(created_at) = ?', Time.zone.today) }

  def user_avatar
    avatar.attached? && avatar || 'user_default_avatar.png'
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  private

  def validate_user_services_uniqueness
    service_ids = user_services.map(&:service_id)
    service_ids.uniq.size != service_ids.size && errors.add(:base, 'Each service must be unique for the user')
  end

  def prepend_adv_to_name
    self.name = name.downcase.gsub('adv.', '').gsub('advocate', '').gsub('adv', '').strip.titleize
    self.name = "Adv. #{name}" if user_summary.fresh_law_graduate?
  end

  def add_advocate?
    user_summary.present?
  end
end

app/controllers/users/confirmations_controller.rb
module Users
  class ConfirmationsController < Devise::ConfirmationsController
    protected

    def after_confirmation_path_for(resource_name, resource)
      AdminMailer.new_user_notification(resource).deliver_later if User.admin.exists?
      super
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController

    protected

    def sign_up(_resource_name, resource)
      AdminMailer.new_user_notification(resource).deliver_later if User.admin.exists?
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_user, only: %i[show verify]

  def index
    @users = User.lawyer
  end

  def show
    @similar_users = User.joins(:services).where(services: { id: @user.services.ids }).where.not(id: @user.id).uniq
  end

  def verify
    if @user.user_summary.update(verified_at: DateTime.now)
      UserMailer.notify_user_about_acount_verification(@user).deliver_later
      redirect_to @user, notice: 'Account has been verified successfully'
    else
      redirect_to root_path, error: 'There is a problem updating account'
    end
  end

  def search
    @users = User.lawyer
    name_search(params[:name_search]) if params[:name_search].present?
    service_search(params[:service_id]) if params[:service_id].present?
    tehsil_bar_search(params[:tehsil_bar]) if params[:tehsil_bar].present?
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('users-list', partial: 'users/user', collection: @users, as: :user)
      end
    end
  end

  def contact_admin
    set_contact_params
    if verify_contact_params
      send_contact_mail
      flash.now[:notice] = 'Thank you for using Adalat.pk, We will come back to you soon!'
      handle_successful_admin_contact
    else
      handle_contact_failure
    end
  end

  def contact_lawyer
    set_contact_params
    @lawyer = User.find(params[:user_id]) if params[:user_id].present?
    if verify_contact_params
      send_contact_mail
      flash.now[:notice] = 'Thank you for using Adalat.pk, We will come back to you soon!'
      handle_successful_lawyer_contact
    else
      handle_contact_failure
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to '/404'
  end

  def name_search(name)
    @users = @users.where('users.name ILIKE ?', "%#{name}%")
  end

  def service_search(service_id)
    @users = @users.joins(:services).where(services: { id: service_id })
  end

  def tehsil_bar_search(tehsil_bar)
    @users = @users.joins(:user_summary).where('user_summaries.tehsil_bar ILIKE ?', "%#{tehsil_bar}%")
  end

  def handle_successful_admin_contact
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('contact-page', partial: 'pages/home_partials/contact_us'),
          turbo_stream.prepend('body_tag', partial: 'shared/toast')
        ]
      end
    end
  end

  def handle_successful_lawyer_contact
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('contact-page', partial: 'users/guest_user_contact_form',
                                              locals: { user_id: @lawyer&.id }),
          turbo_stream.prepend('body_tag', partial: 'shared/toast')
        ]
      end
    end
  end

  def handle_contact_failure
    flash.now[:error] = 'There is a problem receiving your message'
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.prepend('body_tag', partial: 'shared/toast')
      end
    end
  end

  def set_contact_params
    @name = params[:name]
    @email = params[:email]
    @mobile_number = params[:mobile_number]
    @messages = params[:feedback]
  end

  def send_contact_mail
    if @lawyer.present?
      AdminMailer.new_message_for_lawyer(@name, @email, @mobile_number, @messages, @lawyer).deliver_later
    else
      AdminMailer.new_message(@name, @email, @mobile_number, @messages).deliver_later
    end
  end

  def verify_contact_params
    @name.present? && @email.present? && @mobile_number.present? && @messages.present?
  end
end

app/views/users/_guest_user_contact_form.html.erb
<%= form_with url: contact_lawyer_path(user_id: user_id), method: :post do |form| %>
  <div class="field">
    <%= form.text_field :name, placeholder: 'Enter Your Full Name', class: 'form-control mb-3 rounded-0', required: true %>
  </div>
  <div class="field">
    <%= form.telephone_field :mobile_number, placeholder: 'Mobile No.(eg: +920300123456)', class: 'form-control mb-3 rounded-0', required: true %>
  </div>
  <div class="field">
    <%= form.email_field :email, placeholder: 'example@gmail.com', class: 'form-control mb-3 rounded-0', required: true %>
  </div>
  <div class="field">
    <%= form.text_area(:feedback, rows: '5', class: "form-control mb-3 rounded-0", required: true, placeholder: "Your message") %>
  </div>
  <div class="field">
    <%= form.submit 'Send Your Message', class: "btn btn-gold text-white rounded-0 w-100" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="mb-5 pb-5 border-b-gredient">
  <div class="d-flex mb-3">
    <div><%= image_tag user.user_avatar, class: 'rounded-circle user-profile-pic' %></div>
    <div class="align-self-center ms-3">
      <div>
        <span class="fw-bold fs-2"><%= user.name %></span>
        <% if user.user_summary&.verified_at.present? %><span class="badge btn-gold ms-3 align-self-center"><i class="bi bi-patch-check"></i> Verified Lawyer</span> <% end %>
      </div>
      <% if !user.user_summary&.fresh_law_graduate? %>
        <div class="fs-14px">
          <%= user.user_summary.lawyer_type.titleize %>
        </div>
      <% end %>
      <div>
        <% user.services.each do |service| %>
          <span class="fs-14px"> <%= service.name %> <span>|</span> </span>
        <% end %>
      </div>
      <div class="fs-14px">
        <span> <%= user.user_summary&.qualification %></span> | <span><%= user.user_summary&.experience %> year of experience</span>
      </div>
    </div>
  </div>
  <div class="d-flex mb-3 p-4 shadow-sm w-fit-content">
    <div class="me-3"><i class="bi bi-building fs-1 gredient-text"></i></div>
    <table class="fs-small">
      <tr>
        <td>Province</td>
        <td  class="text-secondary ps-3"><%= user.user_summary&.province %></td>
      </tr>
      <tr>
        <td>District</td>
        <td  class="text-secondary ps-3"><%= user.user_summary&.district %></td>
      </tr>
      <tr>
        <td>Tehsil Bar</td>
        <td  class="text-secondary ps-3"><%= user.user_summary&.tehsil_bar %></td>
      </tr>
    </table>
  </div>
  <div class="d-flex">
    <%= link_to 'View Profile', user_path(user.friendly_id), class: 'btn-outline-gold btn w-100 me-2' %>
    <%= link_to 'Contact Now', contact_path, class: 'btn-gold text-white btn w-100 ms-2' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-title">
  <div class="text-white fw-bold h1">Our Amazing Team</div>
  <div class="fw-semibold mt-4">
    <span class="me-2 text-white"><%= link_to 'Home', root_path, class: 'text-decoration-none text-white' %> > </span>
    <span class="gredient-text">Lawyers</span>
  </div>
</div>

<div class="text-center my-5">
  <div class="gredient-text font-monospace">Team</div>
  <div class="fw-bold h2 d-flex justify-content-center">
    <div class="w-30rem p-1">You will entroduce with our expert team <span class="gredient-text"> members</span></div>
  </div>
  <div class="gredient-border"></div>
</div>

<div class="row mx-0">
  <div class="col-md-4 sticky-search-form">
    <div class="transparent-bg3 p-3vw rounded-2 mb-4">
      <div class="fw-bold text-center gredient-text">Search Lawyers</div>
      <%= form_with url: search_users_path, method: :post do |form| %>
        <div class="field mb-3">
          <%= form.label :name, class: 'fs-14px' %><br />
          <%= form.search_field :name_search, oninput: "this.form.requestSubmit()", class: "form-control" %>
        </div>
        <div class="field mb-3">
          <%= form.label :services, class: 'fs-14px' %><br />
          <%= form.select(:service_id, options_from_collection_for_select(Service.all, :id, :name), { include_blank: 'All' },
              { class: 'form-select', onchange: "this.form.requestSubmit()" }) %>
        </div>
        <div class="field mb-3">
          <%= form.label :tehsil_bar, class: 'fs-14px' %><br />
          <%= form.search_field :tehsil_bar, oninput: "this.form.requestSubmit()", class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="mx-lg-5 mx-2" id="users-list">
      <%= render  @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-title">
  <div class="text-white fw-bold h1">Our Amazing Team</div>
  <div class="fw-semibold mt-4">
    <span class="me-2 text-white"><%= link_to 'Home', root_path, class: 'text-decoration-none text-white' %> > </span>
    <span class="gredient-text">
      <%= link_to 'Lawyers', users_path, class: 'text-decoration-none' %> > 
      <%= @user.name %>
    </span>
  </div>
</div>

<div class="row px-3vw mx-0 flex-lg-row justify-content-center m-3vw user-profile">
  <div class="col-md-8">
    <div class="d-flex p-md-0">
      <div class="me-3">
        <%= image_tag(@user.user_avatar, class: 'rounded-circle user-profile-pic shadow-sm')%>
      </div>
      <div class="align-self-center">
        <div class="d-flex flex-wrap"><span class="fw-bold fs-1"><%= @user.name %> </span>
          <% if @user.user_summary&.verified_at.present? %><span class="badge btn-gold ms-3 align-self-center"><i class="bi bi-patch-check-fill"></i> Verified</span> <% end %>
        </div>
        <% if !@user.user_summary&.fresh_law_graduate? %>
          <div class="fs-14px">
            <%= @user.user_summary.lawyer_type.titleize %>
          </div>
        <% end %>
        <div><span class="fw-semibold">Joined: </span>
          <span class="fs-small" > <%= distance_of_time_in_words(@user.created_at, DateTime.now) %> ago</span>
        </div>
        <div class="fs-small"><%= @user.user_summary&.experience %> years of experience</div>
      </div>
    </div>

    <div class="row mx-0 text-center mt-4 shadow">
      <div class="col-md p-4">
        <div class="gredient-text fw-bold fs-2">97%</div>
        <div class="text-secondary">Satisfaction Rate</div>
      </div>
      <div class="col-md p-4">
        <div class="gredient-text fw-bold fs-2">23</div>
        <div class="text-secondary">Cases</div>
      </div>
      <div class="col-md p-4">
        <div class="gredient-text fw-bold fs-2"><%= @user.user_summary&.experience %></div>
        <div class="text-secondary">Years of Experience</div>
      </div>
    </div>

    <div class="mt-3" data-controller="users" data-users-type-value="description">
      <div class="read-less" id="short-description"><%= @user.user_summary&.description&.html_safe %></div>
      <a href="/" class="text-decoration-none" data-action="users#read_more" id="read-more">Read More</a>
      <a href="/" class="text-decoration-none d-none" data-action="users#read_less" id="read-less">Read Less</a>
    </div>

    <div class="row my-3 mx-0">
      <div class="col-md px-0">
        <div class="fw-semibold">Education</div>
        <li><%= @user.user_summary&.qualification %></li>
      </div>
      <div class="col-md px-0">
        <div class="fw-semibold">Locations</div>
        <li>Province | <span class="text-secondary fw-14px"><%= @user.user_summary&.province %></span></li>
        <li>District | <span class="text-secondary fw-14px"><%= @user.user_summary&.district %></span></li>
        <li>Tehsil Bar | <span class="text-secondary fw-14px"><%= @user.user_summary&.tehsil_bar %><span></li>
      </div>
    </div>

    <% if user_signed_in? && ( current_user.admin? || current_user == @user ) %>
      <div class="border-top py-2 row mx-0" >
        <div class="d-flex col-md-6 flex-column text-center">
          <div class="fw-semibold">ID Card</div>
          <div class="border rounded-3">
            <%= image_tag @user.user_summary&.id_card, alt: 'id-card', class: 'user-info-card rounded-3' %>
          </div>
        </div>
        <div class="d-flex col-md-6 flex-column text-center">
          <div class="fw-semibold">Bar Concil Card</div>
          <div class="border rounded-3">
            <%= image_tag @user.user_summary&.bar_concil_card, class: 'user-info-card rounded-3' %>
          </div>
        </div>
      </div>
    <% end %>

    <div data-controller="users" data-users-type-value="services">
      <div class="fw-bold fs-5">Services</div>
      <div class="mt-1"><%= @user.name %> specializes in the following services and procedures</div>
      <div class="flex-d justify-content-start my-3 read-less-services" id="short-services">
        <% @user.services.each do |service| %>
          <div class="p-3 transparent-bg3 rounded">
            <div class="text-center"><%= add_style(service.icon, ' fs-1 gredient-text').html_safe %></div>
            <div class="fw-semibold gredient-text w-10rem"><%= service.name %></div>
            <div class="text-end fs-5 gredient-text"><a href="/services/<%= service.id%>"><i class="bi bi-arrow-right"></i></a></div>
          </div>
        <% end %>
      </div>
      <% if @user.services.count > 4 %>
        <div class="text-end"> 
          <a href="/" class="text-decoration-none fs-14px" data-action="users#read_more" id="read-more-services">See More <i class="bi bi-chevron-down"></i></a>
          <a href="/" class="text-decoration-none d-none fs-14px" data-action="users#read_less" id="read-less-services">See Less <i class="bi bi-chevron-up"></i></a>
        </div>
      <% end %>
    </div>

    <div>
      <div class="gredient-text text-center">Similar Lawyers</div>
      <div class="d-flex justify-content-center">
        <div class="text-center my-4 fw-bold fs-1 w-33rem"> Some lawyers providing same <span class="gredient-text">services</span></div>
      </div>
      <div>
        <%= render @similar_users %>
      </div>
    </div>
  </div>
  <div class="col-md-4 sticky-form">
    <div class="p-3vw text-gold transparent-bg3">
      <div class="fw-bolder mb-5 h4 text-center">Contact <%= @user.name %></div>
      <div id="contact-page"><%= render 'guest_user_contact_form', user_id: @user.id %></div>
    </div>
  </div>
</div>