config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[index show] do
    member do
      get 'verify'
    end
    collection do
      post 'search'
    end
  end

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'
  post '/contact_admin', to: 'users#contact_admin', as: 'contact_admin'
  post '/contact_lawyer', to: 'users#contact_lawyer', as: 'contact_lawyer'

  resources :services, only: %i[index show]
end

app/views/shared/_contact_links.html.erb
<div class="position-fixed chat-link d-flex">
  <a href="https://wa.me/+92-3170730531" target="_blank">
    <i class="bi bi-whatsapp fs-1 text-white px-2 py-1 rounded-2"></i>
  </a>
</div>
<div class="position-fixed call-link d-flex">
  <a href="tel:+92 317-0730531" target="_blank">
    <i class="bi bi-telephone fs-1 text-white px-2 py-1 rounded-2"></i>
  </a>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center footer-bg text-lg-start border-top">
  <div class="container p-4 text-white">
    <div class="row text-start">
      <div class="col-md-2 text-center text-lg-start">
        <a class="navbar-brand" href="/"><%= image_tag 'logo.png', class: 'logo mb-4' %></a>
      </div>
      <div class="col-md-4">
        <div class="fw-semibold mb-3">CONTACT US</div>
        <ul class="nav flex-column">
          <li class="nav-item mb-2 hover-animation"><i class="bi bi-telephone-fill me-2"></i> 
            <span class="fw-lighter"><a href="tel:+92 317-0730531" class="text-decoration-none text-white">+92 317 0730531</a></span></li>
          <li class="nav-item mb-2 hover-animation"><i class="bi bi-envelope-fill me-2"></i> 
            <span class="fw-lighter"><a href = "mailto: contact@adalat.pk" class="text-decoration-none text-white">contact@adalat.pk</a></span></li>
          <li class="nav-item mb-2 hover-animation"><i class="bi bi-house-door-fill me-2"></i>
            <span class="fw-lighter">Al-Adal Tower, 1st Floor, 9 Fane Road, Lahore, Pakistan.</span></li>
        </ul>
      </div>
      <div class="col-md-3">
        <div class="fw-semibold mb-3">PAGES</div>
        <ul class="nav flex-column">
          <li class="nav-item mb-2 hover-animation"><%= link_to '<i class="bi bi-house-door"></i> Home'.html_safe, root_path, class: "text-decoration-none fw-lighter fs-14px text-white" %></li>
          <li class="nav-item mb-2 hover-animation"><%= link_to '<i class="bi bi-tags"></i> Services'.html_safe, services_path, class: "text-decoration-none fw-lighter fs-14px text-white" %></li>
        </ul>
      </div>
      <div class="col-md-3">
        <div class="fw-semibold mb-3">ABOUT US</div>
        <ul class="nav flex-column">
          <li class="nav-item mb-2 hover-animation"><%= link_to '<i class="bi bi-info-circle"></i> ABOUT US'.html_safe, about_page_path, class: "text-decoration-none fw-lighter fs-14px text-white" %></li>
          <li class="nav-item mb-2 hover-animation"><%= link_to '<i class="bi bi-envelope-fill"></i> CONTACT US'.html_safe, contact_path, class: "text-decoration-none fw-lighter fs-14px text-white" %></li>
          <li class="nav-item mb-2 hover-animation"><%= link_to "<i class='bi bi-question-circle'></i> FAQ's".html_safe, faqs_page_path, class: "text-decoration-none fw-lighter fs-14px text-white" %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="d-flex text-white justify-content-between px-5 bg-black pt-3 border-top">
    <p class="fw-light fs-14px">&copy; 2023 Adalat.pk All rights reserved.</p>
    <ul class="list-unstyled d-flex mb-2">
      <li class="ms-3 mt-1 text-secondary fs-14px" >Follow us: </li>
      <li class="ms-3"><a class="link-dark" href="https://github.com/usman-zulfiqar065" target = "_blank"><i class="bi bi-twitter fs-5 text-secondary"></i></a></li>
      <li class="ms-3"><a class="link-dark" href="https://www.linkedin.com/in/usman-zulfiqar/" target = "_blank"><i class="bi bi-facebook fs-5 text-secondary"></i></a></li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="header pt-lg-4">
  <nav class="navbar py-0 navbar-expand-lg navbar-dark px-lg-5 sticky-top transparent-bg">
    <div class="container-fluid mx-lg-5">
      <a class="navbar-brand" href="/"><%= image_tag 'logo.png', class: 'logo' %></a>
      <button class="navbar-toggler me-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link px-lg-4 fw-semibold fs-14px #{ home_page?(params[:controller], params[:action]) }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Lawyers', users_path, class: "nav-link px-lg-4 fw-semibold fs-14px #{ lawyers_page?(params[:controller]) }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Services', services_path, class: "nav-link px-lg-4 fw-semibold fs-14px #{ services_page?(params[:controller]) }" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle fs-14px px-lg-4 fw-semibold" href="#" id="navbarDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              About us
            </a>
            <div class="dropdown-menu rounded-0 p-2 width-25rem" aria-labelledby="navbarDropdownMenuLink2">
              <a href="/about" class="dropdown-item rounded-2 mb-2 hover-pad">
                <div class="fw-semibold fs-14px">About Us</div>
                <div class="fs-14px fw-light ws-normal text-muted">Discover the story behind our mission, explore what we have to offer, 
                  and learn more about who we are</div>
              </a>
              <a href="/contact" class="dropdown-item rounded-2 mb-2 hover-pad">
                <div class="fw-semibold fs-14px">Contact Us</div>
                <div class="fs-14px fw-light ws-normal text-muted">Counsel is just a call away - get in touch with our expert legal team for personalized solutions and reliable guidance</div>
              </a>
              <a href="/faqs" class="dropdown-item rounded-2 mb-2 hover-pad">
                <div class="fw-semibold fs-14px">FAQ's</div>
                <div class="fs-14px fw-light ws-normal text-muted">Have any question? Please have a look at some frequently asked questions</div>
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a href="https://dsjlahore.punjab.gov.pk/" class="nav-link px-lg-4 fw-semibold fs-14px" target="_blank">Case Management</a>
          </li>
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag(set_navbar_user_url, class: "rounded-circle nav-avatar border border-2 border-primary") %>
            </a>
            <ul class="dropdown-menu rounded-0 p-2" aria-labelledby="navbarDropdown">
                <% if user_signed_in? %>
                  <% if current_user.admin? %>
                    <li class="hover-pad"><%= link_to '<i class="bi bi-person-check-fill"></i> Admin Pannel'.html_safe, admin_root_path, class: "dropdown-item nav-link mx-1 text-dark mb-2"%></li>
                  <% end %>
                  <% if current_user.lawyer? %>
                    <li class="hover-pad"><%= link_to '<i class="bi bi-person-bounding-box"></i> My Profile'.html_safe, current_user, class: "dropdown-item nav-link mx-1 text-dark mb-2" %></li>
                  <% end %>
                  <li class="hover-pad"><%= link_to '<i class="bi bi-gear"></i> Update Account'.html_safe, edit_user_registration_path(current_user), class: "dropdown-item nav-link mx-1 text-dark mb-2"%></li>
                  <li class="hover-pad"><hr class="dropdown-divider"></li>
                  <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn text' %></li>
                <% else %>
                  <li class="hover-pad"><%= link_to '<i class="bi bi-box-arrow-in-right"></i> Sign in'.html_safe, new_user_session_path, class: "dropdown-item nav-link mx-1 text-dark mb-2" %></li>
                  <li class="hover-pad"><%= link_to '<i class="bi bi-person-plus"></i> Sign up'.html_safe, new_user_registration_path, class: "dropdown-item nav-link mx-1 text-dark mb-2" %></li>
                <% end %>
            </ul>
          </li>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_toast.html.erb
<% if flash.present? %>
  <div class ="flash" >
    <% flash.each do |flash_type, message| %>
      <div class="flash__message <%= flash_type %>" 
        data-controller="flash"
        data-action="animationend->flash#remove">
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>