config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[index show] do
    member do
      get 'verify'
    end
    collection do
      post 'search'
    end
  end

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'
  post '/contact_admin', to: 'users#contact_admin', as: 'contact_admin'
  post '/contact_lawyer', to: 'users#contact_lawyer', as: 'contact_lawyer'

  resources :services, only: %i[index show]
end

app/views/pages/home_partials/_about_us.html.erb
<div class="px-10vw about mt-2">
  <div class="fw-light fs-14px">About us</div>
  <div class='gredient-line mb-4'><span></span></div>
  <div class="row">
    <div class="col-md-6">
      <div class="fw-bolder h1">We are here to manage your law with <span class="text-gold">experience</span></div>
      <div class="fw-light">
        With a deep understanding of <span class="fw-semibold text-success">Pakistan</span>'s legal landscape, we offer strategic counsel and representation, 
        ensuring your legal needs are met with professionalism and integrity.
      </div>
      <div class="fw-light my-3">
        Whether it's corporate law, family law, or criminal defense, our dedicated team of lawyers is committed 
        to protecting your interests and achieving favorable outcomes.
        <%= link_to 'explore more services', services_path, class: 'text-gold'%>
      </div>
      <div>
        <span class="fs-14px fw-semibold">Call to ask any question </span>
        <span class="fw-bolder h5"><a href="tel:+92 317-0730531" class="text-decoration-none text-gold">+92 317-0730531</a></span>
      </div>
    </div>
    <div class="col-md-6 p-1">
      <%= image_tag 'slider1.jpg', class: 'rounded-5 w-100 shadow-lg h-fill-available' %>
    </div>
  </div>

  <div class="row my-5 justify-content-between">
    <div class="col-md-6 pt-2 d-flex">
      <div class="pe-5">
        <%= image_tag 'signature.png'%>
      </div>
      <div>
        <div class="fw-semibold">Ch. Imran Zulfiqar</div>
        <div class="fw-light text-secondary fs-14px">Advocate High Court</div>
        <div class="fw-light text-secondary fs-14px">Chairman and founder</div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="d-flex justify-content-around">
        <div class="text-center p-3">
          <div class="fw-bolder font-monospace h2 gredient-text">16+</div>
          <div class="fw-semibold">Team Members</div>
        </div>
        <div class="text-center p-3">
          <div class="fw-bolder font-monospace h2 gredient-text"> +2344</div>
          <div class="fw-semibold">Completed Works</div>
        </div>
        <div class="text-center p-3">
          <div class="fw-bolder font-monospace h2 gredient-text">2344</div>
          <div class="fw-semibold">Satisfied Clients</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home_partials/_administrator_user.html.erb
<div class="hover-transition">
  <div class="position-relative">
    <%= image_tag user.user_avatar, class: 'size-19rem grayscale' %>
    <% if user.user_summary&.verified_at.present? %>
      <i class="bi bi-award gredient-text fs-1 position-absolute right-1rem"></i>
    <% end %>
  </div>
  <div class="position-relative bg-white mx-auto text-center p-3 float-div">
    <div class="fw-bold"><%= user.name%></div>
    <div class="fw-light fs-14px">
      Administrator @ Adalat.pk
    </div>
  </div>
</div>

app/views/pages/home_partials/_carosal.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div>
        <%= image_tag 'slider1.jpg', class: 'w-100' %>
        <div class="carousel-1">
          <div class="fw-semibold h3 mb-0">Welcome to Adalat.pk</div>
          <div class="d-flex justify-content-center res-pad2">
            <div class="w-52vw fs-large fw-semibold">Providing Comprehensive Legal Solutions <span class="gredient-text">Nationwide</span></div>
          </div>
          <div><%= link_to 'Contact us today', contact_path, class: 'btn rounded-5 btn-gold fw-bold text-white res-pad px-lg-4 py-lg-3' %></div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div>
        <%= image_tag 'slider2.jpg', class: 'w-100' %>
        <div class="carousel-2 w-100">
          <div>Legal expertise, personalized attention, and unwavering commitment</div>
          <div class="d-flex justify-content-end mb-5vw">
            <div class="w-33rem fs-large fw-semibold">We are your partner in legal matters</div>
          </div>
          <div><%= link_to 'Contact us today', contact_path, class: 'btn rounded-5 btn-gold fw-bold text-white res-pad px-lg-4 py-lg-3' %></div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div>
        <%= image_tag 'slider3.jpg', class: 'w-100' %>
        <div class="carousel-3">
          <div class="fs-2vw fw-semibold text-center">Accomplished Corporate Lawyers</div>
          <div class="d-flex justify-content-center mb-5vw">
            <div class="w-52vw fs-large fw-semibold text-center">We are here to protect any kind of <span class="gredient-text">voilence</span></div>
          </div>
          <div class="text-center"><%= link_to 'Contact us today', contact_path, class: 'btn rounded-5 btn-gold fw-bold text-white res-pad px-lg-4 py-lg-3' %></div>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/home_partials/_contact_us.html.erb
<div class="px-10vw contact mb-5">
  <div class="shadow p-lg-5">
    <div class="fw-light fs-14px mb-1">Contact us</div>
    <div class='gredient-line mb-4'><span></span></div>
    <div class="row mb-4">
      <div class="col-md h2 fw-bolder">
        Feel free to ask any question to <span class="gredient-text">us</span>
      </div>
      <div class="col-md">
        <div class="d-flex">
          <div><i class="bi bi-geo-alt gredient-text me-3 fs-2"></i></div>
          <div class="align-self-center">Al-Adal Tower, 1st Floor, 9 Fane Road, Lahore, Pakistan.</div>
        </div>
      </div>
      <div class="col-md">
        <div class="d-flex">
          <div><i class="bi bi-telephone-forward gredient-text me-3 fs-3"></i></div>
          <div class="align-self-center"><a href="tel:+92 317-0730531" class="text-decoration-none text-black">+92 317 0730531</a></div>
        </div>
        <div class="d-flex">
          <div><i class="bi bi-envelope gredient-text me-3 fs-3"></i></div>
          <div class="align-self-center"><a href = "mailto: contact@adalat.pk" class="text-decoration-none text-black">contact@adalat.pk</a></div>
        </div>
      </div>
    </div>

    <%= form_with url: contact_admin_path, method: :post do |form| %>
      <div class="row">
        <div class="col-md">
          <div class="field">
            <%= form.text_field :name, placeholder: 'Full Name...', class: 'form-control mb-4 rounded-0', required: true %>
          </div>
        </div>
        <div class="col-md">
          <div class="field">
            <%= form.telephone_field :mobile_number, placeholder: 'Mobile No...', class: 'form-control rounded-0 mb-4', required: true %>
          </div>
        </div>
        <div class="col-md">
          <div class="field">
            <%= form.email_field :email, placeholder: 'Email address...', class: 'form-control rounded-0 mb-4', required: true %>
          </div>
        </div>
      </div>
      <div class="field">
        <%= form.text_area(:feedback, rows: '5', class: "form-control mb-4 rounded-0", required: true, placeholder: "Message...") %>
      </div>
      <div class="field">
        <%= form.submit 'Send Your Message', class: "btn btn-gold text-white rounded-0  w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home_partials/_journey.html.erb
<div class="flex-d text-center journey mb-5">
  <div class='year'>
    <div class="fw-semibold">2020</div>
    <div class="dot d-inline-block rounded-5 mt-2"></div>
    <div class="fw-bold mb-3">Started Journey</div>
    <div class="mx-3 fs-14px fw-light">A promising beginning as we set out on our legal journey, dedicated to providing exceptional services and building a trusted law-firm</div>
  </div>
  <div class='year'>
    <div class="fw-semibold">2021</div>
    <div class="dot d-inline-block rounded-5 mt-2"></div>
    <div class="fw-bold mb-3">Empowered Legal Advocacy</div>
    <div class="mx-3 fs-14px fw-light">Empowering lawyers with knowledge and passion, advocating for justice, and making a positive impact within the legal community</div>
  </div>
  <div class='year'>
    <div class="fw-semibold">2022</div>
    <div class="dot d-inline-block rounded-5 mt-2"></div>
    <div class="fw-bold mb-3">Expanded Horizons</div>
    <div class="mx-3 fs-14px fw-light">Breaking barriers and venturing into new legal territories, offering comprehensive solutions to meet diverse client needs</div>
  </div>
  <div class='year'>
    <div class="fw-semibold">2023</div>
    <div class="dot d-inline-block rounded-5 mt-2"></div>
    <div class="fw-bold mb-3">Inspired Client Success</div>
    <div class="mx-3 fs-14px fw-light">Fueled by client successes and stories, we continue to strive for excellence, earning trust through unwavering commitment to our clients</div>
  </div>
</div>

app/views/pages/home_partials/_services.html.erb
<div class="bg-img">
  <div class="px-10vw text-center py-5 mb-5 transparent-bg2"> 
    <div class="gredient-text font-monospace">Services</div>
    <div class="d-flex justify-content-center my-3">
      <div class="fw-bold text-white w-33rem h2">We are here to fight against any violance with 
      <span class="gredient-text">experience</span></div>
    </div>
    <div class="gredient-border"></div>

    <div class="text-end mb-5">
      <%= link_to '<i class="bi bi-arrow-right"></i> view all'.html_safe, services_path, class: 'text-decoration-none text-secondary' %>
    </div>

    <div class="flex-d">
      <%= render @services %>
    </div>
  </div>
</div>

app/views/pages/home_partials/_team.html.erb
<div class="bg-img about">
  <div class="px-10vw py-5 mb-5 transparent-bg2"> 
    <div class="gredient-text font-monospace mb-2">Team member</div>
    <div class='gredient-line mb-4'><span></span></div>
    <div class="row my-3">
      <div class="col-md fw-bold text-white h2">
        <div class="fw-bold text-white h1">We feel very proud for our <span class="gredient-text">experts</span></div>
      </div>
      <div class="col-md text-secondary">
        <div>Meet the faces behind our firm, a team of skilled attorneys ready to tackle your 
              legal challenges with determination and expertise.
        </div>
        <div>
          We believe in continuous growth and professional development, ensuring that our team stays at the 
          forefront of legal trends and best practices.
        </div>
      </div>
    </div>

    <div class="text-end">
      <%= link_to '<i class="bi bi-arrow-right"></i> view all'.html_safe, users_path, class: 'text-decoration-none text-secondary' %>
    </div>

    <div class="flex-d mt-5">
      <%= render partial: 'pages/home_partials/team_member', collection: @lawyers, as: :user %>
    </div>
    <div class="flex-d mt-5">
      <%= render partial: 'pages/home_partials/administrator_user', collection: @administrators, as: :user %>
    </div>
  </div>
</div>

app/views/pages/home_partials/_team_member.html.erb
<div class="hover-transition">
  <div class="position-relative">
    <%= image_tag user.user_avatar, class: 'size-19rem grayscale' %>
    <% if user.user_summary&.verified_at.present? %>
      <i class="bi bi-award gredient-text fs-1 position-absolute right-1rem"></i>
    <% end %>
  </div>
  <div class="position-relative bg-white mx-auto text-center p-3 float-div">
    <div class="fw-bold"><%= user.name%></div>
    <% if !user.user_summary&.fresh_law_graduate? %>
      <div class="fw-light fs-14px"><%= user.user_summary.lawyer_type.titleize %></div>
    <% end %>
    <div><%= link_to 'Contact Now', user_path(user.friendly_id), class: 'gredient-text fs-14px' %></div>
  </div>
</div>

app/views/pages/home_partials/_testimonials.html.erb
<div class="container-fluid px-10vw position-relative top-74px">
  <div class="row">
    <a href="/contact" class="col-md shadow p-5 bg-white hover hover-eff btn rounded-0">
      <div class="d-flex">
        <i class="bi bi-telephone-plus fs-2 me-4 text-gold gold-shadow"></i>
        <div>
          <div class="text-secondary">Need help?</div>
          <div class="fw-bolder fs-2 eff-child">Consult now</div>
        </div>
      </div>
    </a>
    <a href="/users/sign_up" class="col-md shadow p-5 bg-black text-white btn rounded-0">
      <div class="d-flex">
        <i class="bi bi-link-45deg fs-1 me-4 text-gold gold-shadow"></i>
        <div>
          <div class="text-secondary">Join us</div>
          <div class="fw-bolder fs-2">As a lawyer</div>
        </div>
      </div>
    </a>
    <a href="/services" class="col-md shadow p-5 bg-white hover-eff btn rounded-0">
      <div class="d-flex">
        <i class="bi bi-receipt-cutoff fs-2 me-4 text-gold gold-shadow"></i>
        <div>
          <div class="text-secondary">Explore more</div>
          <div class="fw-bolder fs-2 eff-child">Services</div>
        </div>
      </div>
    </a>
  </div>
</div>